language: java
jdk:
- oraclejdk8

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.m2/wrapper"

before_install:
- mvn clean package -Dmaven.javadoc.skip=true -B -V -e

install:
- mvn install

script:
- mvn cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash)

# use latest java version available instead of travis default
addons:
  apt:
    packages:
    - oracle-java8-installer

sudo: false
